export const loginApi = "/auth/login";
export const registerApi ="/auth/register-user-api"
export const healthProviderApi ="/auth/health-provider-detail"
export const verifyOtpApi ="/auth/verifyOtp"
export const autoLoginApi = "auth/auto-login";
export const checkTokenIsValidApi = "/auth/token-is-valid";
export const logoutApi = "/auth/logout";
export const getAllUsersApi = "/auth/get-all-users";
export const getUserDetailsApi = "/auth/get-user-details";
export const updateUserDetailsApi = "/auth/update-user-details";
export const getalladmins = "/auth/get-all-admins-api"
